# Generated by Django 3.2.23 on 2024-01-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0002_learningpath_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='subtitle',
            field=models.CharField(max_length=255),
        ),
    ]
