# Generated by Django 4.2.16 on 2025-03-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0007_replace_uuid_with_learningpathkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningpathstep',
            name='relative_due_date_in_days',
        ),
    ]
