# Generated by Django 4.2.20 on 2025-04-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_paths", "0011_replace_learningpath_image_url_with_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningpath",
            name="subtitle",
            field=models.TextField(blank=True),
        ),
    ]
