# Generated by Django 4.2.16 on 2025-03-28 09:54

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_paths', '0005_learningpathstep_weight_learningpathgradingcriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpathenrollment',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp of enrollment or un-enrollment. To be explicitly set when performing a learner enrollment.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningpathenrollment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the learner is enrolled or not in the Learning Path'),
        ),
        migrations.CreateModel(
            name='LearningPathEnrollmentAllowed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_paths.learningpath')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('email', 'learning_path')},
            },
        ),
    ]
