# Generated by Django 4.2.20 on 2025-04-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning_paths", "0008_remove_learningpathstep_relative_due_date_in_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningpath",
            name="slug",
        ),
    ]
