# Generated by Django 4.2.20 on 2025-04-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_paths", "0009_remove_learningpath_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningpath",
            name="invite_only",
            field=models.BooleanField(
                default=True,
                help_text="If enabled, only staff can enroll users and only enrolled users can see the learning path.",
                verbose_name="Invite only",
            ),
        ),
    ]
