# Generated by Django 4.2.20 on 2025-04-27 20:14

from django.db import migrations, models
import learning_paths.models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_paths", "0010_learningpath_invite_only"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningpath",
            name="image_url",
        ),
        migrations.AddField(
            model_name="learningpath",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image representing this Learning Path.",
                null=True,
                upload_to=learning_paths.models.LearningPath._learning_path_image_upload_path,
                verbose_name="Image",
            ),
        ),
    ]
