# Generated by Django 4.2.23 on 2025-07-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_paths", "0014_remove_learningpath_duration_in_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acquiredskill",
            name="level",
            field=models.PositiveIntegerField(
                blank=True, help_text="The skill level associated with this course.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="requiredskill",
            name="level",
            field=models.PositiveIntegerField(
                blank=True, help_text="The skill level associated with this course.", null=True
            ),
        ),
    ]
